FROM node:23-alpine

WORKDIR /app
COPY package*.json ./

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
ENV CHOKIDAR_USEPOLLING=true

RUN npm install
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
