services:
  db:
    image: mysql:8.0
    container_name: kortowo-db-ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: kortowo_test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    tmpfs:
      - /var/lib/mysql
    networks:
      - ci-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "testuser", "-ptestpass"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s

  backend:
    container_name: kortowo-backend-ci
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=test
      - DB_HOST=db
      - DB_USER=testuser
      - DB_PASSWORD=testpass
      - DB_NAME=kortowo_test
      - DB_DIALECT=mysql
      - DB_PORT=3306
      - JWT_SECRET=ci-test-secret
      - API_PORT=3000
      - CLIENT_URL=http://localhost:5173
    ports:
      - "3000:3000"
    networks:
      - ci-network
    depends_on:
      db:
        condition: service_healthy

networks:
  ci-network:
    driver: bridge
