services:
  db:
    image: mysql:8.0
    container_name: kortowo-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - diploma-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 60s  

  adminer:
    image: adminer:latest
    container_name: kortowo-adminer
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=pepa-linha-dark
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - diploma-network
    restart: unless-stopped

  backend:
    container_name: kortowo-backend
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_DIALECT=${DB_DIALECT}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET:-change-this-secret-in-dev}
      - API_PORT=${API_PORT}
      - CLIENT_URL=${CLIENT_URL}
      - LOG_LEVEL=debug
      - LOG_DIR=/var/log/kortowo/backend
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "${API_PORT}:3000"
    volumes:
      - ./server:/app:cached
      - ./data/backend-logs:/var/log/kortowo/backend
      - /app/node_modules
    networks:
      - diploma-network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: vite-frontend
    ports:
      - "${VITE_API_PORT}:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    networks:
      - diploma-network

  loki:
    image: grafana/loki:3.1.1
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/loki-config.yml
      - loki_data:/loki
    networks:
      - diploma-network

  promtail:
    image: grafana/promtail:3.1.1
    container_name: promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
      - ./data/backend-logs:/var/log/kortowo/backend:ro
      - promtail_positions:/tmp
    depends_on:
      - loki
    networks:
      - diploma-network

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    networks:
      - diploma-network

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - loki
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
      - grafana_data:/var/lib/grafana
    networks:
      - diploma-network

  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - diploma-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - diploma-network

volumes:
  db_data:
    driver: local
  prometheus_data:
    driver: local
  portainer_data:
    driver: local
  loki_data:
    driver: local
  promtail_positions:
    driver: local
  grafana_data:
    driver: local

networks:
  diploma-network:
    driver: bridge
